version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: proforma_server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    restart: unless-stopped
    networks:
      - proforma_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: proforma_frontend
    ports:
      - "3003:80"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - proforma_network

networks:
  proforma_network:
    driver: bridge
